Lambda sqs updates (#7571)
* Revert to static logger

Using ILogger results in an error when running the lambda function:
Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[TriggerMessageHandler]' while attempting to activate 'TriggerMessageHandler'.

* Remove InputLoopService

* Update to .NET 10

* RTM tweaks

---------

Co-authored-by: Brandon Ording <bording@gmail.com>